module.exports = {
    DATABASE_NAME: "Mon-VIE-VIA",
    DATABASE_STUDY_LEVEL_COLLECTION: "studyLevels",
    DATABASE_MISSION_TYPES_COLLECTION: "missionTypes",
    DATABASE_ENTREPRISE_TYPES_COLLECTION: "entrepriseTypes",
    DATABASE_ACTIVITY_SECTORS_COLLECTION: "activitySectors",
    DATABASE_SPECIALIZATIONS_COLLECTION: "specializations",
    DATABASE_ENTERPRISES_COLLECTION: "enterprise",
    DATABASE_OFFERS_COLLECTION: "offers",
    DATABASE_GEOGRAPHIC_ZONES_COLLECTION: "geographicZones",
    DATABASE_COUNTRIES_COLLECTION: "countries",
    DATABASE_CITIES_COLLECTION: "cities",
    STUDY_LEVEL_PROGRESS_BAR: "Inserting study levels",
    MISSION_TYPES_PROGRESS_BAR: "Inserting mission types",
    ENTREPRISE_TYPES_PROGRESS_BAR: "Inserting entreprise types",
    ACTIVITY_SECTORS_PROGRESS_BAR: "Inserting activity sectors",
    SPECIALIZATIONS_PROGRESS_BAR: "Inserting specializations",
    ENTERPRISES_PROGRESS_BAR: "Inserting enterprise",
    OFFERS_PROGRESS_BAR: "Inserting offers",
    GEOGRAPHIC_ZONES_PROGRESS_BAR: "Inserting geographic zones",
    COUNTRIES_PROGRESS_BAR: "Inserting countries",
    CITIES_PROGRESS_BAR: "Inserting cities",
    ENTERPRISES_SECTION: "Loading enterprises",
    DATASET_SECTION: "Loading dataset",
    OFFERS_SECTION: "Loading offers",
    LOCATIONS_SECTION: "Loading locations",
    STUDY_LEVEL_UPDATE_PROGRESS_BAR: "Updating study levels",
    MISSION_TYPES_UPDATE_PROGRESS_BAR: "Updating mission types",
    ENTREPRISE_TYPES_UPDATE_PROGRESS_BAR: "Updating entreprise types",
    ACTIVITY_SECTORS_UPDATE_PROGRESS_BAR: "Updating activity sectors",
    SPECIALIZATIONS_UPDATE_PROGRESS_BAR: "Updating specializations",
    ENTERPRISES_UPDATE_PROGRESS_BAR: "Updating enterprise",
    OFFERS_UPDATE_PROGRESS_BAR: "Updating offers",
    GEOGRAPHIC_ZONES_UPDATE_PROGRESS_BAR: "Updating geographic zones",
    COUNTRIES_UPDATE_PROGRESS_BAR: "Updating countries",
    CITIES_UPDATE_PROGRESS_BAR: "Updating cities",
    ENTERPRISES_UPDATE_SECTION: "Updating enterprises",
    DATASET_UPDATE_SECTION: "Updating dataset",
    OFFERS_UPDATE_SECTION: "Updating offers",
    LOCATIONS_UPDATE_SECTION: "Updating locations"
}