module.exports = {
    DATABASE_NAME: "Mon-VIE-VIA",
    DATABASE_STUDY_LEVEL_COLLECTION: "studyLevels",
    DATABASE_MISSION_TYPES_COLLECTION: "missionTypes",
    DATABASE_ENTREPRISE_TYPES_COLLECTION: "entrepriseTypes",
    DATABASE_ACTIVITY_SECTORS_COLLECTION: "activitySectors",
    DATABASE_SPECIALIZATIONS_COLLECTION: "specializations",
    DATABASE_ENTERPRISES_COLLECTION: "enterprise",
    DATABASE_OFFERS_COLLECTION: "offers",
    DATABASE_GEOGRAPHIC_ZONES_COLLECTION: "geographicZones",
    DATABASE_COUNTRIES_COLLECTION: "countries",
    DATABASE_CITIES_COLLECTION: "cities"
}